# Generated by Django 4.2.4 on 2023-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaFalsaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=255)),
                ('xi', models.FloatField()),
                ('xs', models.FloatField()),
                ('error', models.FloatField()),
                ('iteracions', models.IntegerField()),
            ],
        ),
    ]
