# Generated by Django 4.2.4 on 2023-10-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_remove_reglafalsamodel_funcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglafalsamodel',
            name='error',
        ),
    ]
