# Generated by Django 4.2.6 on 2023-10-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_biseccionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='newton1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=255)),
                ('xi', models.FloatField()),
                ('xs', models.FloatField()),
                ('tol', models.FloatField()),
                ('iteraciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=255)),
                ('xi', models.FloatField()),
                ('xs', models.FloatField()),
                ('tol', models.FloatField()),
                ('iteraciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=255)),
                ('xi', models.FloatField()),
                ('xs', models.FloatField()),
                ('tol', models.FloatField()),
                ('iteraciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='secanteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=255)),
                ('xi', models.FloatField()),
                ('xs', models.FloatField()),
                ('tol', models.FloatField()),
                ('iteraciones', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ReglaFalsaModel',
        ),
    ]
