# Generated by Django 4.2.6 on 2023-10-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_newton1model_pfmodel_rfmodel_secantemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secantemodel',
            old_name='tol',
            new_name='Tol',
        ),
        migrations.RenameField(
            model_name='secantemodel',
            old_name='iteraciones',
            new_name='niter',
        ),
        migrations.RenameField(
            model_name='secantemodel',
            old_name='xi',
            new_name='x0',
        ),
        migrations.RenameField(
            model_name='secantemodel',
            old_name='xs',
            new_name='x1',
        ),
    ]
