# Generated by Django 4.2.6 on 2023-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_alter_biseccionmodel_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfmodel',
            old_name='tol',
            new_name='Tol',
        ),
        migrations.RenameField(
            model_name='pfmodel',
            old_name='iteraciones',
            new_name='niter',
        ),
        migrations.RenameField(
            model_name='pfmodel',
            old_name='xi',
            new_name='x0',
        ),
        migrations.RemoveField(
            model_name='pfmodel',
            name='xs',
        ),
        migrations.AddField(
            model_name='pfmodel',
            name='error',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pfmodel',
            name='funcg',
            field=models.CharField(default='vbdb', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pfmodel',
            name='resultado',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
