# Generated by Django 4.2.4 on 2023-11-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_alter_biseccionmodel_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='rmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=255)),
                ('x0', models.FloatField()),
                ('tol', models.FloatField()),
                ('iteraciones', models.IntegerField()),
                ('resultado', models.CharField(default=' ', max_length=300)),
            ],
        ),
    ]
