# Generated by Django 4.2.6 on 2023-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0009_rmmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secantemodel',
            name='error',
        ),
        migrations.AddField(
            model_name='secantemodel',
            name='resultado',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
