# Generated by Django 4.2.6 on 2023-11-02 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0009_rename_tol_pfmodel_tol_and_more'),
        ('module1', '0009_rmmodel'),
    ]

    operations = [
    ]
