# Generated by Django 4.2.4 on 2023-11-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0010_merge_20231101_2109'),
        ('module1', '0010_remove_secantemodel_error_secantemodel_resultado'),
    ]

    operations = [
    ]
