# Generated by Django 4.2.4 on 2023-11-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0012_gsmodel_sormodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gsModel',
        ),
    ]
