# Generated by Django 4.2.4 on 2023-11-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0013_delete_gsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='gsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.JSONField()),
                ('b', models.JSONField()),
                ('x0', models.JSONField()),
                ('tol', models.FloatField()),
                ('niter', models.IntegerField()),
            ],
        ),
    ]
