# Generated by Django 4.2.4 on 2023-11-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0015_alter_gsmodel_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmodel',
            name='x0',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
