# Generated by Django 4.2.6 on 2023-11-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0016_alter_gsmodel_x0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sormodel',
            name='a',
        ),
        migrations.AlterField(
            model_name='sormodel',
            name='b',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sormodel',
            name='x0',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sormodel',
            name='A',
            field=models.JSONField(default=3),
            preserve_default=False,
        ),
    ]
