# Generated by Django 4.2.6 on 2023-11-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0016_alter_gsmodel_x0'),
    ]

    operations = [
        migrations.AddField(
            model_name='secantemodel',
            name='Terror',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
