# Generated by Django 4.2.6 on 2023-11-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0017_secantemodel_terror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfmodel',
            old_name='iteraciones',
            new_name='Terror',
        ),
        migrations.RenameField(
            model_name='rfmodel',
            old_name='tol',
            new_name='Tol',
        ),
        migrations.RenameField(
            model_name='rfmodel',
            old_name='xi',
            new_name='x0',
        ),
        migrations.RenameField(
            model_name='rfmodel',
            old_name='xs',
            new_name='x1',
        ),
        migrations.AddField(
            model_name='rfmodel',
            name='niter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfmodel',
            name='resultado',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
