# Generated by Django 4.2.6 on 2023-11-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0018_alter_sormodel_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sormodel',
            name='w',
            field=models.FloatField(default=1.25),
            preserve_default=False,
        ),
    ]
