# Generated by Django 4.2.6 on 2023-11-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0019_alter_sormodel_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='lagrange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.JSONField()),
                ('y', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='sormodel',
            name='error',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
