# Generated by Django 4.2.6 on 2023-11-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0021_alter_sormodel_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sormodel',
            name='error',
            field=models.IntegerField(default=0),
        ),
    ]
