# Generated by Django 4.2.6 on 2023-11-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0018_rename_iteraciones_rfmodel_terror_and_more'),
        ('module1', '0026_alter_sormodel_error'),
    ]

    operations = [
    ]
