# Generated by Django 4.2.6 on 2023-11-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0027_merge_20231119_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='jacobiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.JSONField()),
                ('b', models.JSONField(blank=True, null=True)),
                ('x0', models.JSONField(blank=True, null=True)),
                ('tol', models.FloatField()),
                ('niter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vandermondemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.JSONField()),
                ('y', models.JSONField()),
            ],
        ),
    ]
