# Generated by Django 4.2.4 on 2023-11-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0028_newtonint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newtonint',
            new_name='newtonintModel',
        ),
    ]
