# Generated by Django 4.2.6 on 2023-11-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0028_jacobimodel_vandermondemodel'),
        ('module1', '0030_alter_newtonintmodel_pol'),
    ]

    operations = [
    ]
