# Generated by Django 4.2.6 on 2023-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0031_merge_20231122_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vandermondemodel',
            name='x',
        ),
        migrations.RemoveField(
            model_name='vandermondemodel',
            name='y',
        ),
        migrations.AddField(
            model_name='vandermondemodel',
            name='resultado',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='vandermondemodel',
            name='xin',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vandermondemodel',
            name='yin',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
